version: '1.0'

services:
  main:
    container_name: "DemystData_frontend"
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:8080"
    command: npm run serve
    env_file:
      - .env

